version: 0.2

phases:
    install:
        commands:
            - sudo apt-get install software-properties-common -y 
            - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            - sudo apt-get install nodejs -y
            - npm install -g @angular/cli
    pre_build:
        commands:
            - npm install
    build:
        commands:
            - ng build --prod
artifacts:
    files:
        - "**/*"
    discard-paths: no
    base-directory: dist
